name: Update README with Art

on: workflow_dispatch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install art  # アスキーアートライブラリをインストール

    - name: Generate ASCII art
      run: python generate_art.py

    - name: Update README
      run: |
        echo "### Latest Art" > README.md
        cat art.txt >> README.md

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with new art"
        git push
